Repository PUNCH-Cyber/stoq-plugins-public, pull requests merged in 2020-07, with the labels that each got.

#107 Fix LIEF plugin configuration retrieval
  lief/lief/lief.py
  lief/lief/lief.stoq
  lief/setup.py
Labels: bug

#109 Add Azure Blob Storage plugin
  README.md
  azure_blob/MANIFEST.in
  azure_blob/README.md
  azure_blob/azure_blob/__init__.py
  azure_blob/azure_blob/azure_blob.py
  azure_blob/azure_blob/azure_blob.stoq
  azure_blob/requirements.txt
  azure_blob/setup.py
Labels: new plugin

#112 Add initial Azure Sentinel plugin
  README.md
  sentinel/MANIFEST.in
  sentinel/README.md
  sentinel/requirements.txt
  sentinel/sentinel/__init__.py
  sentinel/sentinel/sentinel.py
  sentinel/sentinel/sentinel.stoq
  sentinel/setup.py
Labels: new plugin

#113 Plugin enhancements and additions
  README.md
  sentinel/MANIFEST.in
  sentinel/README.md
  sentinel/requirements.txt
  sentinel/sentinel/__init__.py
  sentinel/sentinel/sentinel.py
  sentinel/sentinel/sentinel.stoq
  sentinel/setup.py
  yara/tests/test_yara.py
  yara/yarascan/yarascan.py
Labels: enhancement, new plugin

#114 Fix variable error in sentinel
  sentinel/sentinel/sentinel.py
  sentinel/sentinel/sentinel.stoq
  sentinel/setup.py
Labels: bug

#115 Fix another variable in sentinel
  sentinel/sentinel/sentinel.py
  sentinel/sentinel/sentinel.stoq
  sentinel/setup.py
Labels: bug
